
releases:
  - version: 1.1.0
    release_note: Improvements release
    date: 2014-10-17 23:00:00
    sources:
      - googlePlay
      - appStore

  - version: 1.1.0
    release_note: Improvements release
    date: 2014-10-17 23:00:00
    sources:
      - googlePlay
      - appStore


  # - version: 1.0.0
  #   release_note: Improvements release
  #   date: 2014-10-10 23:00:00
  #   sources:
  #     - name: googlePlay
  #       url: https://play.google.com/store/apps/details?id=app.hiddify.com
  #       date: 2014-10-17 23:00:00
  #       can_ignore_release: true
  #     - appStore

  # - version: 1.0.0
  #   release_note: Improvements release
  #   date: 2014-10-10 23:00:00
  #   postavki:
  #     - googlePlay
  #     - appStore

  # - version: 1.0.0
  #   release_note: Improvements release
  #   date: 2014-10-10 23:00:00
  #   postavki:
  #     - source: 
  #         name: googlePlay
  #         url: https://play.google.com/store/apps/details?id=app.hiddify.com
  #       date: 2014-10-17 23:00:00
  #     - appStore




version:
release_note: Improvements release
date: 2014-10-10 23:00:00
source: 
  name: googlePlay
  url: https://play.google.com/store/apps/details?id=app.hiddify.com
  platforms: [android]


list:
  - version:
    release_note: Improvements release
    date: 2014-10-10 23:00:00
    source: 
      name: googlePlay
      url: https://play.google.com/store/apps/details?id=app.hiddify.com
      platforms: [android]
  - version:
    release_note: Improvements release
    date: 2014-10-10 23:00:00
    source: 
      name: googlePlay
      url: https://play.google.com/store/apps/details?id=app.hiddify.com
      platforms: [android]