
releases:
  - version: 1.1.0
    status: recommended
    release_note: Improvements release
    date: 2014-10-17 23:00:00
    stores:
      - googlePlay
      - appStore

  - version: 1.0.0
    release_note: Improvements release
    date: 2014-10-10 23:00:00
    stores:
      - googlePlay
      - appStore
  
