name: dev_kit

packages:
  - .

scripts:
  # Исправляет линты и форматирует все файлы в проекте. 
  fix_format: 'melos exec "dart fix --apply && dart format ."'

  # Запускает build_runner build
  build: 'melos exec "dart run build_runner build -d"'

  # Запускает build_runner watch в core package
  watch: 'melos exec "dart run build_runner watch -d"'

  pub_get: 'melos exec "flutter pub get"'
  
