name: dev_kit_workspace

packages:
  - api_wrap
  - app_logger
  - app_onboarding
  - dev_kit
  - riverpod_async_builder
  - riverpod_validator

scripts:
  # Исправляет линты и форматирует все файлы в проекте. 
  fix_format: 'melos exec "dart fix --apply && dart format ."'

  # Запускает build_runner build
  build: 'melos exec "dart run build_runner build -d"'

  # Запускает build_runner watch
  watch: 'melos exec "dart run build_runner watch -d"'

  pub_get: 'melos exec "flutter pub get"'
  
