name: dev_kit
description: Dev kit
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  proxima_logger: ^0.7.2
  path_provider: ^2.1.1
  dio: ^5.4.0

  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
 
  flutter_svg: ^2.0.9
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
