name: riverpod_utils
description: Utility extensions for working with Riverpod providers and notifiers
version: 0.1.0
repository: https://github.com/StarProxima/dev_kit/tree/develop/riverpod_utils
homepage: https://github.com/StarProxima/dev_kit

environment:
  sdk: ^3.3.0

dependencies:
  riverpod: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
