name: app_logger
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.2

  # MIT
  cr_json_widget: ^1.1.1

  # Network
  # MIT
  dio: ^5.4.0
  # MIT
  chopper: ^7.0.10
  # MIT
  proxima_logger: ^0.7.2

  # BSD
  package_info_plus: ^4.2.0

  # MIT
  uuid: ^4.3.3

  # MIT
  app_settings: ^5.1.1

  # BSD
  path_provider: ^2.1.2
  # BSD-3-Clause
  path: ^1.8.3

  # MIT
  inspector: ^2.1.0

  # BSD-3-Clause
  shared_preferences: ^2.2.2
  # MIT
  split_view: ^3.2.1

  # unknown
  # https://pub.dev/packages/synchronized/license
  synchronized: ^3.1.0

  # BSD-3-Clause
  js: ^0.6.7

  # BSD-3-Clause
  # https://stackoverflow.com/a/70757512
  platform: ^3.1.2

  # Apache-2.0
  infinite_scroll_pagination: ^4.0.0
  # MIT
  worker_manager: ^6.3.1

  # BSD-2-Clause
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.crefter.app_logger.app_logger
        pluginClass: AppLoggerPlugin
      ios:
        pluginClass: AppLoggerPlugin
      web:
        pluginClass: AppLoggerWeb
        fileName: app_logger_web.dart

