name: app_update_checker
description: Check for updates to your app with the possibility of deprecation, required updates and various app stores
version: 0.0.8
homepage: https://github.com/StarProxima/dev_kit/tree/develop/app_update_checker
screenshots:
 - description: 'App Update Checker Thumbnail'
   path: assets/package_thumbnail.png

topics:
  - app
  - update
  - checker
  - upgrader
  
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2

  package_info_plus: '>=4.2.0 <9.0.0'
  # os_detect: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  project_kit:
    path: ../unpublished/project_kit
