name: api_wrap
description: Error handling, rate limiting and retry in one ergonomic api
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.0.0
  dio: ^5.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
