name: api_wrap
description: Error handling, rate limiting, delay and retry in one ergonomic api
version: 0.0.1
repository: https://github.com/StarProxima/dev_kit/tree/develop/api_wrap
homepage: https://github.com/StarProxima/dev_kit
screenshots:
 - description: 'Package Thumbnail'
   path: assets/package_thumbnail.png

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  dio: ^5.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
