name: dev_kit
description: A set of developer utilities for flutter projects
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # api_wrap:
  #   git:
  #     url: https://sea.xdev.team/StarProxima/dev_kit
  #     ref: package-restructuring
  #     path: api_wrap

  # riverpod_async_builder:
  #   path: ../riverpod_async_builder

  # riverpod_utils:
  #   path: ../riverpod_utils
    
  # riverpod_validator:
  #   path: ../riverpod_validator


  collection: ^1.18.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  proxima_logger: ^0.7.2
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.1

  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.4
  theme_tailor_annotation: ^2.1.0
  auto_exporter_annotation: ^1.0.1
 
  flutter_svg: ^2.0.9
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_exporter: ^3.0.2
  melos: ^4.1.0
