name: riverpod_validator
description: Allows you to create user data validators directly in Notifier`s using Riverpod
version: 0.0.1
repository: https://github.com/StarProxima/dev_kit/tree/develop/api_wrap
homepage: https://github.com/StarProxima/dev_kit
screenshots:
 - description: 'Package Thumbnail'
   path: assets/package_thumbnail.png

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.0.0
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_lints: ^3.0.1
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_exporter: ^3.0.2
  melos: ^4.1.0