name: riverpod_validator
description: Allows you to create user data validators directly in Notifier`s using Riverpod
version: 0.0.2
repository: https://github.com/StarProxima/dev_kit/tree/develop/riverpod_validator
homepage: https://github.com/StarProxima/dev_kit
screenshots:
 - description: 'Package Thumbnail'
   path: assets/package_thumbnail.png

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.0.0
  riverpod: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_lints: ^3.0.1